#Ownership: Arnav Sawant

# Use the official Node.js image as the base image
FROM node:16

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

RUN npm i --save-dev @types/cors

# Copy the rest of the application code to the container
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose the port that the app will run on
EXPOSE 8081

# Command to run the application
CMD ["npx", "ts-node", "index.ts"]
